function shell(content, title = "ქართული ამბების რედაქტორი") {
  return `<!doctype html><html lang="ka"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title} | Investors.ge</title><style>
  :root{color-scheme:light;--ink:#10261f;--green:#007a52;--line:#dce8e2;--paper:#f5f8f6;--muted:#61736c;--red:#a73333}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.shell{width:min(1100px,calc(100% - 28px));margin:0 auto;padding:36px 0 70px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:28px}.brand{font-size:22px;font-weight:850}.brand span{color:var(--green)}h1{font-size:clamp(28px,5vw,48px);letter-spacing:-.04em;margin:8px 0}p{color:var(--muted);line-height:1.6}.card{background:white;border:1px solid var(--line);border-radius:18px;padding:22px;box-shadow:0 10px 35px rgba(24,67,52,.06)}button,.button{border:0;border-radius:10px;padding:11px 15px;background:var(--green);color:white;font-weight:750;cursor:pointer}.secondary{background:#e7f2ed;color:var(--green)}.danger{background:#fff0f0;color:var(--red);border:1px solid #f0cccc}.login{max-width:470px;margin:11vh auto}.login label{display:block;font-weight:700;margin:20px 0 8px}.login input,textarea{width:100%;border:1px solid var(--line);border-radius:10px;padding:12px;font:inherit}.error{color:var(--red);font-size:13px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.queue{display:grid;gap:16px}.story h2{font-size:20px;margin:6px 0 10px}.meta{font-size:12px;color:var(--muted);margin-bottom:16px}.story label{display:block;font-size:12px;font-weight:800;margin:13px 0 6px}.story textarea{resize:vertical;min-height:76px}.story textarea.summary{min-height:110px}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:15px}.empty{text-align:center;padding:50px 20px}.history{margin-top:14px;padding-top:14px;border-top:1px solid var(--line);font-size:12px}.history-item{padding:9px 0;border-bottom:1px solid var(--line)}a{color:var(--green)}@media(max-width:620px){.top,.toolbar{align-items:flex-start;flex-direction:column}.actions button{flex:1}}
  </style></head><body><main class="shell">${content}</main></body></html>`;
}

export function renderEditorialLogin(error = "") {
  return shell(`<section class="card login"><div class="brand">Investors<span>.ge</span></div><h1>რედაქტორის შესვლა</h1><p>ეს სივრცე განკუთვნილია მხოლოდ Investors.ge რედაქტორისთვის.</p><form id="login"><label for="password">პაროლი</label><input id="password" type="password" autocomplete="current-password" required><p class="error" id="error">${error}</p><button type="submit">შესვლა</button></form></section><script>
  document.querySelector('#login').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;const response=await fetch('/api/editorial/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:document.querySelector('#password').value})});if(response.ok){location.reload();return}document.querySelector('#error').textContent='პაროლი არასწორია';button.disabled=false});
  </script>`, "რედაქტორის შესვლა");
}

export function renderEditorialDashboard() {
  return shell(`<header class="top"><div><div class="brand">Investors<span>.ge</span></div><h1>ქართული ამბების რედაქტორი</h1><p>საჯაროდ გამოჩნდება მხოლოდ დამტკიცებული მასალა, რომლის სათაურშიც არის შეთანხმებული საკვანძო სიტყვა.</p></div><button class="secondary" id="logout">გასვლა</button></header><div class="toolbar"><b id="count">იტვირთება…</b><button class="secondary" id="refresh">განახლება</button></div><section class="queue" id="queue"></section><script>
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function storyMarkup(article){return '<article class="card story" data-id="'+esc(article.id)+'"><div class="meta">'+esc(article.source)+' · '+esc(new Date(article.published_at).toLocaleString('ka-GE'))+' · რევიზია '+esc(article.revision)+'</div><a href="'+esc(article.source_url||article.url)+'" target="_blank" rel="noopener noreferrer">პირველწყაროს გახსნა ↗</a><label>ქართული სათაური</label><textarea class="title">'+esc(article.title_ka)+'</textarea><label>ქართული შეჯამება</label><textarea class="summary">'+esc(article.summary_ka)+'</textarea><div class="actions"><button data-action="approve">დამტკიცება და გამოქვეყნება</button><button class="danger" data-action="reject">უარყოფა</button><button class="secondary" data-action="history">ისტორია</button></div><div class="history" hidden></div></article>'}
  async function load(){const response=await fetch('/api/editorial/pending',{cache:'no-store'});if(response.status===401){location.reload();return}const data=await response.json();document.querySelector('#count').textContent='რიგშია: '+data.count;const queue=document.querySelector('#queue');if(!data.articles.length){queue.innerHTML='<div class="card empty"><h2>რიგი ცარიელია</h2><p>ახალი შესაფერისი ქართული ამბავი ჯერ არ შემოსულა.</p></div>';return}queue.innerHTML=data.articles.map(storyMarkup).join('')}
  async function review(card,action){const button=card.querySelector('[data-action="'+action+'"]');button.disabled=true;const response=await fetch('/api/editorial/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({articleId:card.dataset.id,action,titleKa:card.querySelector('.title').value,summaryKa:card.querySelector('.summary').value})});const data=await response.json();if(!response.ok){alert(data.error||'მოქმედება ვერ შესრულდა');button.disabled=false;return}card.remove();load()}
  async function history(card){const box=card.querySelector('.history');if(!box.hidden){box.hidden=true;return}const response=await fetch('/api/editorial/history?id='+encodeURIComponent(card.dataset.id),{cache:'no-store'});const data=await response.json();box.innerHTML=data.revisions?.length?data.revisions.map(item=>'<div class="history-item"><b>რევიზია '+esc(item.revision)+' · '+esc(item.editorial_status)+'</b><br>'+esc(item.reviewer_role)+' · '+esc(new Date(item.created_at).toLocaleString('ka-GE'))+'</div>').join(''):'<p>წინა რევიზია არ არის.</p>';box.hidden=false}
  document.querySelector('#queue').addEventListener('click',event=>{const action=event.target.dataset.action;if(!action)return;const card=event.target.closest('.story');action==='history'?history(card):review(card,action)});document.querySelector('#refresh').onclick=load;document.querySelector('#logout').onclick=async()=>{await fetch('/api/editorial/logout',{method:'POST'});location.reload()};load();
  </script>`);
}
